name: Node CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Setup dev
        run: |
          npm ci
      - name: Code format check
        run: |
          npm run lint
        env:
          CI: true
      - name: Test
        run: |
          npm run build --if-present
          npm test
        env:
          CI: true
